services:
  db:
    image: postgres
    container_name: go-social-db
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"

  redis:
      image: redis:6.2-alpine
      restart: unless-stopped
      container_name: redis
      ports:
        - "6379:6379"
      command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart:
      unless-stopped
  mongodb:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_URL=mongodb://admin:adminpassword@mongo:27017/
    ports:
      - "8082:8081"
    networks:
      - backend
  
volumes:
  db-data:
  mongo-data:

networks:
  backend:
    driver: bridge