// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Tag struct {
	Name     string  `json:"name"`
	Count    int32   `json:"count"`
	LastUsed *string `json:"lastUsed,omitempty"`
}
