name: Update Version and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract latest version from CHANGELOG.md
        id: get_version
        run: |
          VERSION=$(grep -oP '\[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in cmd/api/main.go
        run: |
          sed -i.bak "s/var version = \".*\"/var version = \"${{ env.VERSION }}\"/" cmd/api/main.go && rm -f cmd/api/main.go.bak

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add cmd/api/main.go
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version to ${{ env.VERSION }}"
          git push origin main